# Generated by Django 5.1.1 on 2024-10-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='startup_register1',
        ),
        migrations.DeleteModel(
            name='startup_register10',
        ),
        migrations.DeleteModel(
            name='startup_register2',
        ),
        migrations.DeleteModel(
            name='startup_register3',
        ),
        migrations.DeleteModel(
            name='startup_register4',
        ),
        migrations.DeleteModel(
            name='startup_register5',
        ),
        migrations.DeleteModel(
            name='startup_register6',
        ),
        migrations.DeleteModel(
            name='startup_register7',
        ),
        migrations.DeleteModel(
            name='startup_register8',
        ),
    ]
