# Generated by Django 5.1.3 on 2024-11-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='startup_register1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRNnumber', models.CharField(max_length=9, unique=True)),
                ('Doc', models.ImageField(upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='startup_register10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/videos')),
            ],
        ),
        migrations.CreateModel(
            name='startup_register2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=250)),
                ('q2', models.CharField(max_length=250)),
                ('q3', models.CharField(max_length=250)),
                ('q4', models.CharField(max_length=250)),
                ('q5', models.CharField(max_length=250)),
                ('q6', models.CharField(max_length=250)),
                ('q7', models.CharField(max_length=250)),
                ('q8', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='startup_register3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=250)),
                ('q2', models.CharField(max_length=250)),
                ('q3', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='startup_register4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=250)),
                ('q2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='startup_register5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=250)),
                ('q2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='startup_register6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=250)),
                ('q2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='startup_register7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=250)),
                ('q2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='startup_register8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=250)),
                ('q2', models.CharField(max_length=250)),
                ('q3', models.CharField(max_length=250)),
            ],
        ),
    ]
