# Generated by Django 5.1 on 2024-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_signin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='location',
            field=models.CharField(default='Not Specified', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signin',
            name='mobile',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signin',
            name='profession',
            field=models.CharField(default='Not Specified', max_length=30),
            preserve_default=False,
        ),
    ]
