# Generated by Django 5.1.1 on 2024-11-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_signin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup_register2',
            name='q1',
        ),
    ]
