# Generated by Django 5.1.1 on 2024-11-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_startup_register2_q1'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup_register2',
            name='q1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
