# Generated by Django 5.1 on 2024-11-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_signin_location_signin_mobile_signin_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='mobile',
            field=models.BigIntegerField(default=None, unique=True),
        ),
    ]
