# Generated by Django 5.1 on 2024-11-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_signin_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
