# Generated by Django 5.1 on 2024-11-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_signin_mobile_signin_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='mobile_num',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
