# Generated by Django 5.1 on 2024-11-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_signin_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='mobile_num',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
