# Generated by Django 5.1 on 2024-11-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_signin_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='mobile_num',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
