# Generated by Django 5.1 on 2024-11-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_signin_mobile_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='mobile_num',
            new_name='mobile',
        ),
    ]
