# Generated by Django 5.1 on 2024-11-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_signin_groups_signin_is_active_signin_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='user_type',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
