# Generated by Django 5.1 on 2024-11-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_startup_register1_sign_startup_register10_sign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup_register1',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='startup_register10',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='startup_register2',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='startup_register3',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='startup_register4',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='startup_register5',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='startup_register6',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='startup_register7',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='startup_register8',
            name='sign',
        ),
    ]
