# Generated by Django 5.1 on 2024-12-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_startup_register1_user_startup_register10_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup_register1',
            name='Company_Name',
            field=models.CharField(max_length=50, null=True, blank=True, default="null"),
        ),
        migrations.AddField(
            model_name='startup_register1',
            name='Founder_Name',
            field=models.CharField(max_length=100, null=True, blank=True, default="null"),
        ),
    ]
