# Generated by Django 5.1 on 2024-12-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_startup_register1_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup_register1',
            name='Company_Name',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup_register1',
            name='Founder_Name',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
    ]
