# Generated by Django 5.1 on 2024-12-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_startup_register1_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup_register4',
            name='q1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='startup_register4',
            name='q2',
            field=models.CharField(max_length=500),
        ),
    ]
